config/routes.rb
Teams::Application.routes.draw do

  resources :feature_teams do
    resources :members
    resources :deploys
  end

  resources :members
  resources :deploys
  resources :rooms
  resources :servers
  resources :repositories

   root :to => 'feature_teams#index'

end

app/models/feature_team.rb
require 'active_support/inflector'

class FeatureTeam < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships

  has_many :deploys
  has_many :repositories, through: :deploys

  belongs_to :server
  belongs_to :room, dependent: :destroy
  belongs_to :quarterback, class_name: 'Member', foreign_key: 'quarterback_id'

  accepts_nested_attributes_for :members

  attr_accessible :branch, :name, :slug, :room_id, :server_id, :quarterback_id, :members_attributes

  before_validation :generate_branch
  before_create :create_room, :assign_server
  before_save :update_slug

  validates :name, presence: true, uniqueness: true
  validates :branch, presence: true,
    uniqueness: { message: '' }, on: :save

  def to_param
    "#{id}-#{slug}"
  end

  def generate_branch
    if self[:branch].blank?
      self[:branch] = "develop_" + name.parameterize.underscore if name
    else
      self[:branch] = "develop_" + self[:branch].downcase
    end
  end

  def create_room
    if room = Room.create(name: name)
      self.room = room
    end
  end

  def assign_server
    self[:server_id] = Server.next_available.id
  end

  def update_slug
    self[:slug] = name.parameterize if name
  end
end

app/controllers/feature_teams_controller.rb
class FeatureTeamsController < ApplicationController
  before_filter :available_servers

  # GET /feature_teams
  # GET /feature_teams.json
  def index
    @feature_teams = FeatureTeam.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feature_teams }
    end
  end

  # GET /feature_teams/1
  # GET /feature_teams/1.json
  def show
    @feature_team = FeatureTeam.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feature_team }
    end
  end

  # GET /feature_teams/new
  # GET /feature_teams/new.json
  def new
    @feature_team = FeatureTeam.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feature_team }
    end
  end

  # GET /feature_teams/1/edit
  def edit
    @feature_team = FeatureTeam.find(params[:id])
  end

  # POST /feature_teams
  # POST /feature_teams.json
  def create
    @feature_team = FeatureTeam.new(params[:feature_team])

    respond_to do |format|
      if @feature_team.save
        format.html { redirect_to @feature_team, notice: 'Feature team was successfully created.' }
        format.json { render json: @feature_team, status: :created, location: @feature_team }
      else
        format.html { render action: "new" }
        format.json { render json: @feature_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feature_teams/1
  # PUT /feature_teams/1.json
  def update
    @feature_team = FeatureTeam.find(params[:id])

    respond_to do |format|
      if @feature_team.update_attributes(params[:feature_team])
        format.html { redirect_to @feature_team, notice: 'Feature team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feature_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feature_teams/1
  # DELETE /feature_teams/1.json
  def destroy
    @feature_team = FeatureTeam.find(params[:id])
    @feature_team.destroy

    respond_to do |format|
      format.html { redirect_to feature_teams_url }
      format.json { head :no_content }
    end
  end


  private

    def available_servers
      @available_servers = Server.available
    end
end

app/helpers/feature_teams_helper.rb
module FeatureTeamsHelper
  def member_count(feature_team)
    names = feature_team.members.collect(&:name).to_sentence
    content_tag(:abbr, feature_team.members.count, title: names)
  end
end

app/views/feature_teams/_form.html.haml
= form_for @feature_team do |f|
  - if @feature_team.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feature_team.errors.count, "error")} prohibited this feature_team from being saved:"
      %ul
        - @feature_team.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :branch
    = f.text_field :branch

  - if controller.action_name == :edit
    .field
      = f.label :server
      = f.select :server_id, @available_servers.collect{ |s| [s.subdomain, s.id] }, include_blank: true


  -#= f.link_to_add 'Add Another Member', :members

  .actions
    = f.submit 'Save'

app/views/feature_teams/edit.html.haml
%h1 Editing Feature Team

= render 'form'

= link_to 'Show', @feature_team
\|
= link_to 'Back', feature_teams_path

app/views/feature_teams/index.html.haml
%h1 Feature Teams

- if @feature_teams.any?
  %table.table.table-hover
    %thead
      %tr
        %th Name
        %th Members
        %th Branch
        %th Room
        %th Server
        %th

    %tbody
      - @feature_teams.each do |feature_team|
        %tr
          %td= link_to feature_team.name, feature_team
          %td.center= member_count(feature_team)
          %td= feature_team.branch
          %td= link_to feature_team.room.name, room_path(feature_team.room)
          %td= link_to feature_team.server.hostname, server_path(feature_team.server)
          %td= action_buttons feature_team

- else
  %p No feature teams yet.

%br

= link_to 'New Feature Team', new_feature_team_path

app/views/feature_teams/new.html.haml
%h1 New Feature Team

= render 'form'

= link_to 'Back', feature_teams_path

app/views/feature_teams/show.html.haml
%h2= @feature_team.name

%p
  %b Branch:
  = @feature_team.branch

%p
  %b Room:
  = link_to @feature_team.room.name, room_path(@feature_team.room)

%p
  %b Server:
  = link_to @feature_team.server.hostname, @feature_team.server

%h4 Members
- if @feature_team.members.any?
  %ul
    - @feature_team.members.each do |member|
      %li #{link_to(member.name, member)}#{@feature_team.quarterback_id == member.id ? " (Quarterback)" : nil }
- else
  %p No members yet

%h4 Deploys
- if @feature_team.deploys.any?
  %table.table
    - @feature_team.deploys.recent(5).each do |deploy|
      %tr
        %td= link_to deploy.short_sha, deploy
        %td #{time_ago_in_words(deploy.created_at)} ago
- else
  %p No deploys yet

= link_to 'Edit', edit_feature_team_path(@feature_team)
\|
= link_to 'Back', feature_teams_path