config/routes.rb
Teams::Application.routes.draw do

  resources :feature_teams do
    resources :members
    resources :deploys
  end

  resources :members
  resources :deploys
  resources :rooms
  resources :servers
  resources :repositories

   root :to => 'feature_teams#index'

end

app/models/repository.rb
class Repository < ActiveRecord::Base
  has_many :deploys
  has_many :feature_teams, through: :deploys

  attr_accessible :name

  def github_url
    "https://github.com/Healthagen/#{name}"
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  # GET /repositories
  # GET /repositories.json
  def index
    @repositories = Repository.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @repositories }
    end
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
    @repository = Repository.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @repository }
    end
  end

  # GET /repositories/new
  # GET /repositories/new.json
  def new
    @repository = Repository.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @repository }
    end
  end

  # GET /repositories/1/edit
  def edit
    @repository = Repository.find(params[:id])
  end

  # POST /repositories
  # POST /repositories.json
  def create
    @repository = Repository.new(params[:repository])

    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
        format.json { render json: @repository, status: :created, location: @repository }
      else
        format.html { render action: "new" }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /repositories/1
  # PUT /repositories/1.json
  def update
    @repository = Repository.find(params[:id])

    respond_to do |format|
      if @repository.update_attributes(params[:repository])
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.json
  def destroy
    @repository = Repository.find(params[:id])
    @repository.destroy

    respond_to do |format|
      format.html { redirect_to repositories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/repositories/_form.html.haml
= form_for @repository do |f|
  - if @repository.errors.any?
    #error_explanation
      %h2= "#{pluralize(@repository.errors.count, "error")} prohibited this repository from being saved:"
      %ul
        - @repository.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/repositories/edit.html.haml
%h1 Editing repository

= render 'form'

= link_to 'Show', @repository
\|
= link_to 'Back', repositories_path

app/views/repositories/index.html.haml
%h1 Listing repositories

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @repositories.each do |repository|
    %tr
      %td= repository.name
      %td= link_to 'Show', repository
      %td= link_to 'Edit', edit_repository_path(repository)
      %td= link_to 'Destroy', repository, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Repository', new_repository_path

app/views/repositories/new.html.haml
%h1 New repository

= render 'form'

= link_to 'Back', repositories_path

app/views/repositories/show.html.haml
%p
  %b Name:
  = @repository.name

= link_to 'Edit', edit_repository_path(@repository)
\|
= link_to 'Back', repositories_path