config/routes.rb
Teams::Application.routes.draw do

  resources :feature_teams do
    resources :members
    resources :deploys
  end

  resources :members
  resources :deploys
  resources :rooms
  resources :servers
  resources :repositories

   root :to => 'feature_teams#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_one :feature_team

  attr_accessible :name, :room_id
  before_create :create_hipchat_room
  validates :name, presence: true

  def create_hipchat_room
    @hipchat = HipChat::API.new(Rails.configuration.app[:hipchat][:token])

    room_name = "[FT] #{self.name}"

    unless ![:development, :test].include?(Rails.env)
      Rails.logger.info "ROOM WAS REALLY CREATED!!! Oh noes!"
      response = @hipchat.rooms_create(room_name, 148845).parsed_response
    else
      Rails.logger.info "ROOM NOT REALLY CREATED"
      response = { 'room' => { 'room_id' => '11111' } }
    end

    if response['room']
      self['name'] = room_name
      self['room_id'] = response['room']['room_id']
    elsif response['error']
      response['error']['message']
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rooms }
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(params[:room])

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render json: @room, status: :created, location: @room }
      else
        format.html { render action: "new" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.haml
= form_for @room do |f|
  - if @room.errors.any?
    #error_explanation
      %h2= "#{pluralize(@room.errors.count, "error")} prohibited this room from being saved:"
      %ul
        - @room.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :room_id
    = f.text_field :room_id
  .actions
    = f.submit 'Save'

app/views/rooms/edit.html.haml
%h1 Editing room

= render 'form'

= link_to 'Show', @room
\|
= link_to 'Back', rooms_path

app/views/rooms/index.html.haml
%h1 Listing rooms

%table
  %tr
    %th Name
    %th Room
    %th
    %th
    %th

  - @rooms.each do |room|
    %tr
      %td= room.name
      %td= room.room_id
      %td= link_to 'Show', room
      %td= link_to 'Edit', edit_room_path(room)
      %td= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Room', new_room_path

app/views/rooms/new.html.haml
%h1 New room

= render 'form'

= link_to 'Back', rooms_path

app/views/rooms/show.html.haml
%p
  %b Name:
  = @room.name
%p
  %b Room:
  = @room.room_id

= link_to 'Edit', edit_room_path(@room)
\|
= link_to 'Back', rooms_path