config/routes.rb
Teams::Application.routes.draw do

  resources :feature_teams do
    resources :members
    resources :deploys
  end

  resources :members
  resources :deploys
  resources :rooms
  resources :servers
  resources :repositories

   root :to => 'feature_teams#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :memberships
  has_many :feature_teams, through: :memberships

  attr_accessible :email, :hipchat_id, :first_name, :middle_name, :last_name

  before_validation :get_hipchat_id

  validates :hipchat_id, presence: true
  validates :first_name, :last_name, presence: true

  default_scope order(:last_name)

  def get_hipchat_id
    unless self[:hipchat_id].present? || ['development', 'test'].include?(Rails.env)
      hipchat = HipChat::API.new(Rails.configuration.app[:hipchat][:token])
      user = hipchat.users_show(self.email)

      if user.key?('user') && !user.key?('error')
        hipchat_id = user['user']['user_id']
        self[:hipchat_id] = hipchat_id
      else
        message = user['error']['code'] == 404 ? 'No hipchat user was found with that email address.' : user['error']['message']
        errors.add(:hipchat_id, message)
      end
    else
      self[:hipchat_id] = '11111' if [:development, :test].include?(Rails.env)
    end
  end

  def name
    [first_name, middle_name, last_name].compact.join(' ')
  end

  def formatted_name
    "#{last_name}, #{[first_name, middle_name].compact.join(' ')}"
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
  def list_feature_teams(member)
     if member.feature_teams.any?
       member.feature_teams.collect { |f| link_to f.name, f }.to_sentence.html_safe
     else
      'none'
     end
  end
end

app/views/members/_form.html.haml
= form_for @member do |f|
  - if @member.errors.any?
    #error_explanation
      %h2= "#{pluralize(@member.errors.count, "error")} prohibited this member from being saved:"
      %ul
        - @member.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :middle_name
    = f.text_field :middle_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :hipchat_id, "Hipchat ID"
    = f.text_field :hipchat_id, placeholder: 'optional'
  .actions
    = f.submit 'Save'

app/views/members/edit.html.haml
%h1 Editing member

= render 'form'

= link_to 'Show', @member
\|
= link_to 'Back', members_path

app/views/members/index.html.haml
%h1 Members

- if @members.any?
  %table.table.table-hover
    %thead
      %tr
        %th Name
        %th Email
        %th Feature Teams
        %th Actions

    %tbody
      - @members.each do |member|
        %tr
          %td= link_to(member.formatted_name, member)
          %td= mail_to member.email
          %td= list_feature_teams(member)
          %td= action_buttons(member)

- else
  %p No members yet.

%br

= link_to 'New Member', new_member_path

app/views/members/new.html.haml
%h1 New member

= render 'form'

= link_to 'Back', members_path

app/views/members/show.html.haml
%h2= @member.name

%p
  %b Email:
  = @member.email

%p
  %b Hipchat ID:
  = @member.hipchat_id

%p
  %b Feature Teams:
  - if @member.feature_teams.any?
    = list_feature_teams(@member)
  - else
    none

= link_to 'Edit', edit_member_path(@member)
\|
= link_to 'Back', members_path